// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cloudtower-go-sdk/models"
)

// AddVMNicReader is a Reader for the AddVMNic structure.
type AddVMNicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddVMNicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddVMNicOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddVMNicOK creates a AddVMNicOK with default headers values
func NewAddVMNicOK() *AddVMNicOK {
	return &AddVMNicOK{}
}

/* AddVMNicOK describes a response with status code 200, with default header values.

Ok
*/
type AddVMNicOK struct {
	Payload []*models.WithTaskVM
}

func (o *AddVMNicOK) Error() string {
	return fmt.Sprintf("[POST /add-vm-nic][%d] addVmNicOK  %+v", 200, o.Payload)
}
func (o *AddVMNicOK) GetPayload() []*models.WithTaskVM {
	return o.Payload
}

func (o *AddVMNicOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
