// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Yuyz0112/cloudtower-go-sdk/models"
)

// NewCreateVMVolumeParams creates a new CreateVMVolumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateVMVolumeParams() *CreateVMVolumeParams {
	return &CreateVMVolumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVMVolumeParamsWithTimeout creates a new CreateVMVolumeParams object
// with the ability to set a timeout on a request.
func NewCreateVMVolumeParamsWithTimeout(timeout time.Duration) *CreateVMVolumeParams {
	return &CreateVMVolumeParams{
		timeout: timeout,
	}
}

// NewCreateVMVolumeParamsWithContext creates a new CreateVMVolumeParams object
// with the ability to set a context for a request.
func NewCreateVMVolumeParamsWithContext(ctx context.Context) *CreateVMVolumeParams {
	return &CreateVMVolumeParams{
		Context: ctx,
	}
}

// NewCreateVMVolumeParamsWithHTTPClient creates a new CreateVMVolumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateVMVolumeParamsWithHTTPClient(client *http.Client) *CreateVMVolumeParams {
	return &CreateVMVolumeParams{
		HTTPClient: client,
	}
}

/* CreateVMVolumeParams contains all the parameters to send to the API endpoint
   for the create Vm volume operation.

   Typically these are written to a http.Request.
*/
type CreateVMVolumeParams struct {

	// RequestBody.
	RequestBody []*models.VMVolumeCreationParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create Vm volume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMVolumeParams) WithDefaults() *CreateVMVolumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create Vm volume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMVolumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create Vm volume params
func (o *CreateVMVolumeParams) WithTimeout(timeout time.Duration) *CreateVMVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create Vm volume params
func (o *CreateVMVolumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create Vm volume params
func (o *CreateVMVolumeParams) WithContext(ctx context.Context) *CreateVMVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create Vm volume params
func (o *CreateVMVolumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create Vm volume params
func (o *CreateVMVolumeParams) WithHTTPClient(client *http.Client) *CreateVMVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create Vm volume params
func (o *CreateVMVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestBody adds the requestBody to the create Vm volume params
func (o *CreateVMVolumeParams) WithRequestBody(requestBody []*models.VMVolumeCreationParams) *CreateVMVolumeParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the create Vm volume params
func (o *CreateVMVolumeParams) SetRequestBody(requestBody []*models.VMVolumeCreationParams) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVMVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
