// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Yuyz0112/cloudtower-go-sdk/models"
)

// CreateVlanReader is a Reader for the CreateVlan structure.
type CreateVlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateVlanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateVlanOK creates a CreateVlanOK with default headers values
func NewCreateVlanOK() *CreateVlanOK {
	return &CreateVlanOK{}
}

/* CreateVlanOK describes a response with status code 200, with default header values.

Ok
*/
type CreateVlanOK struct {
	Payload []*models.WithTaskNfsExport
}

func (o *CreateVlanOK) Error() string {
	return fmt.Sprintf("[POST /create-nfs-export][%d] createVlanOK  %+v", 200, o.Payload)
}
func (o *CreateVlanOK) GetPayload() []*models.WithTaskNfsExport {
	return o.Payload
}

func (o *CreateVlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVlanBadRequest creates a CreateVlanBadRequest with default headers values
func NewCreateVlanBadRequest() *CreateVlanBadRequest {
	return &CreateVlanBadRequest{}
}

/* CreateVlanBadRequest describes a response with status code 400, with default header values.

CreateVlanBadRequest create vlan bad request
*/
type CreateVlanBadRequest struct {
	Payload string
}

func (o *CreateVlanBadRequest) Error() string {
	return fmt.Sprintf("[POST /create-nfs-export][%d] createVlanBadRequest  %+v", 400, o.Payload)
}
func (o *CreateVlanBadRequest) GetPayload() string {
	return o.Payload
}

func (o *CreateVlanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
