// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cloudtower-go-sdk/models"
)

// NewGetOrganizationsConnectionParams creates a new GetOrganizationsConnectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationsConnectionParams() *GetOrganizationsConnectionParams {
	return &GetOrganizationsConnectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationsConnectionParamsWithTimeout creates a new GetOrganizationsConnectionParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationsConnectionParamsWithTimeout(timeout time.Duration) *GetOrganizationsConnectionParams {
	return &GetOrganizationsConnectionParams{
		timeout: timeout,
	}
}

// NewGetOrganizationsConnectionParamsWithContext creates a new GetOrganizationsConnectionParams object
// with the ability to set a context for a request.
func NewGetOrganizationsConnectionParamsWithContext(ctx context.Context) *GetOrganizationsConnectionParams {
	return &GetOrganizationsConnectionParams{
		Context: ctx,
	}
}

// NewGetOrganizationsConnectionParamsWithHTTPClient creates a new GetOrganizationsConnectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationsConnectionParamsWithHTTPClient(client *http.Client) *GetOrganizationsConnectionParams {
	return &GetOrganizationsConnectionParams{
		HTTPClient: client,
	}
}

/* GetOrganizationsConnectionParams contains all the parameters to send to the API endpoint
   for the get organizations connection operation.

   Typically these are written to a http.Request.
*/
type GetOrganizationsConnectionParams struct {

	// RequestBody.
	RequestBody *models.GetOrganizationsConnectionRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organizations connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsConnectionParams) WithDefaults() *GetOrganizationsConnectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organizations connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsConnectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organizations connection params
func (o *GetOrganizationsConnectionParams) WithTimeout(timeout time.Duration) *GetOrganizationsConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organizations connection params
func (o *GetOrganizationsConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organizations connection params
func (o *GetOrganizationsConnectionParams) WithContext(ctx context.Context) *GetOrganizationsConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organizations connection params
func (o *GetOrganizationsConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organizations connection params
func (o *GetOrganizationsConnectionParams) WithHTTPClient(client *http.Client) *GetOrganizationsConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organizations connection params
func (o *GetOrganizationsConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestBody adds the requestBody to the get organizations connection params
func (o *GetOrganizationsConnectionParams) WithRequestBody(requestBody *models.GetOrganizationsConnectionRequestBody) *GetOrganizationsConnectionParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the get organizations connection params
func (o *GetOrganizationsConnectionParams) SetRequestBody(requestBody *models.GetOrganizationsConnectionRequestBody) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationsConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
