// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cloudtower-go-sdk/models"
)

// NewGetNvmfNamespacesConnectionParams creates a new GetNvmfNamespacesConnectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNvmfNamespacesConnectionParams() *GetNvmfNamespacesConnectionParams {
	return &GetNvmfNamespacesConnectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNvmfNamespacesConnectionParamsWithTimeout creates a new GetNvmfNamespacesConnectionParams object
// with the ability to set a timeout on a request.
func NewGetNvmfNamespacesConnectionParamsWithTimeout(timeout time.Duration) *GetNvmfNamespacesConnectionParams {
	return &GetNvmfNamespacesConnectionParams{
		timeout: timeout,
	}
}

// NewGetNvmfNamespacesConnectionParamsWithContext creates a new GetNvmfNamespacesConnectionParams object
// with the ability to set a context for a request.
func NewGetNvmfNamespacesConnectionParamsWithContext(ctx context.Context) *GetNvmfNamespacesConnectionParams {
	return &GetNvmfNamespacesConnectionParams{
		Context: ctx,
	}
}

// NewGetNvmfNamespacesConnectionParamsWithHTTPClient creates a new GetNvmfNamespacesConnectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNvmfNamespacesConnectionParamsWithHTTPClient(client *http.Client) *GetNvmfNamespacesConnectionParams {
	return &GetNvmfNamespacesConnectionParams{
		HTTPClient: client,
	}
}

/* GetNvmfNamespacesConnectionParams contains all the parameters to send to the API endpoint
   for the get nvmf namespaces connection operation.

   Typically these are written to a http.Request.
*/
type GetNvmfNamespacesConnectionParams struct {

	// RequestBody.
	RequestBody *models.GetNvmfNamespacesConnectionRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get nvmf namespaces connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNvmfNamespacesConnectionParams) WithDefaults() *GetNvmfNamespacesConnectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get nvmf namespaces connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNvmfNamespacesConnectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) WithTimeout(timeout time.Duration) *GetNvmfNamespacesConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) WithContext(ctx context.Context) *GetNvmfNamespacesConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) WithHTTPClient(client *http.Client) *GetNvmfNamespacesConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestBody adds the requestBody to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) WithRequestBody(requestBody *models.GetNvmfNamespacesConnectionRequestBody) *GetNvmfNamespacesConnectionParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the get nvmf namespaces connection params
func (o *GetNvmfNamespacesConnectionParams) SetRequestBody(requestBody *models.GetNvmfNamespacesConnectionRequestBody) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *GetNvmfNamespacesConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
