// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cloudtower-go-sdk/models"
)

// NewGetReportTemplatesConnectionParams creates a new GetReportTemplatesConnectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReportTemplatesConnectionParams() *GetReportTemplatesConnectionParams {
	return &GetReportTemplatesConnectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReportTemplatesConnectionParamsWithTimeout creates a new GetReportTemplatesConnectionParams object
// with the ability to set a timeout on a request.
func NewGetReportTemplatesConnectionParamsWithTimeout(timeout time.Duration) *GetReportTemplatesConnectionParams {
	return &GetReportTemplatesConnectionParams{
		timeout: timeout,
	}
}

// NewGetReportTemplatesConnectionParamsWithContext creates a new GetReportTemplatesConnectionParams object
// with the ability to set a context for a request.
func NewGetReportTemplatesConnectionParamsWithContext(ctx context.Context) *GetReportTemplatesConnectionParams {
	return &GetReportTemplatesConnectionParams{
		Context: ctx,
	}
}

// NewGetReportTemplatesConnectionParamsWithHTTPClient creates a new GetReportTemplatesConnectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReportTemplatesConnectionParamsWithHTTPClient(client *http.Client) *GetReportTemplatesConnectionParams {
	return &GetReportTemplatesConnectionParams{
		HTTPClient: client,
	}
}

/* GetReportTemplatesConnectionParams contains all the parameters to send to the API endpoint
   for the get report templates connection operation.

   Typically these are written to a http.Request.
*/
type GetReportTemplatesConnectionParams struct {

	// RequestBody.
	RequestBody *models.GetReportTemplatesConnectionRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get report templates connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReportTemplatesConnectionParams) WithDefaults() *GetReportTemplatesConnectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get report templates connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReportTemplatesConnectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) WithTimeout(timeout time.Duration) *GetReportTemplatesConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) WithContext(ctx context.Context) *GetReportTemplatesConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) WithHTTPClient(client *http.Client) *GetReportTemplatesConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestBody adds the requestBody to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) WithRequestBody(requestBody *models.GetReportTemplatesConnectionRequestBody) *GetReportTemplatesConnectionParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the get report templates connection params
func (o *GetReportTemplatesConnectionParams) SetRequestBody(requestBody *models.GetReportTemplatesConnectionRequestBody) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *GetReportTemplatesConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
