// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Yuyz0112/cloudtower-go-sdk/models"
)

// NewGetGlobalSettingsesConnectionParams creates a new GetGlobalSettingsesConnectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGlobalSettingsesConnectionParams() *GetGlobalSettingsesConnectionParams {
	return &GetGlobalSettingsesConnectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGlobalSettingsesConnectionParamsWithTimeout creates a new GetGlobalSettingsesConnectionParams object
// with the ability to set a timeout on a request.
func NewGetGlobalSettingsesConnectionParamsWithTimeout(timeout time.Duration) *GetGlobalSettingsesConnectionParams {
	return &GetGlobalSettingsesConnectionParams{
		timeout: timeout,
	}
}

// NewGetGlobalSettingsesConnectionParamsWithContext creates a new GetGlobalSettingsesConnectionParams object
// with the ability to set a context for a request.
func NewGetGlobalSettingsesConnectionParamsWithContext(ctx context.Context) *GetGlobalSettingsesConnectionParams {
	return &GetGlobalSettingsesConnectionParams{
		Context: ctx,
	}
}

// NewGetGlobalSettingsesConnectionParamsWithHTTPClient creates a new GetGlobalSettingsesConnectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGlobalSettingsesConnectionParamsWithHTTPClient(client *http.Client) *GetGlobalSettingsesConnectionParams {
	return &GetGlobalSettingsesConnectionParams{
		HTTPClient: client,
	}
}

/* GetGlobalSettingsesConnectionParams contains all the parameters to send to the API endpoint
   for the get global settingses connection operation.

   Typically these are written to a http.Request.
*/
type GetGlobalSettingsesConnectionParams struct {

	// RequestBody.
	RequestBody *models.GetGlobalSettingsesConnectionRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get global settingses connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlobalSettingsesConnectionParams) WithDefaults() *GetGlobalSettingsesConnectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get global settingses connection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlobalSettingsesConnectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) WithTimeout(timeout time.Duration) *GetGlobalSettingsesConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) WithContext(ctx context.Context) *GetGlobalSettingsesConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) WithHTTPClient(client *http.Client) *GetGlobalSettingsesConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestBody adds the requestBody to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) WithRequestBody(requestBody *models.GetGlobalSettingsesConnectionRequestBody) *GetGlobalSettingsesConnectionParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the get global settingses connection params
func (o *GetGlobalSettingsesConnectionParams) SetRequestBody(requestBody *models.GetGlobalSettingsesConnectionRequestBody) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *GetGlobalSettingsesConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
