// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Yuyz0112/cloudtower-go-sdk/models"
)

// NewGetImagesConnectorParams creates a new GetImagesConnectorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImagesConnectorParams() *GetImagesConnectorParams {
	return &GetImagesConnectorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImagesConnectorParamsWithTimeout creates a new GetImagesConnectorParams object
// with the ability to set a timeout on a request.
func NewGetImagesConnectorParamsWithTimeout(timeout time.Duration) *GetImagesConnectorParams {
	return &GetImagesConnectorParams{
		timeout: timeout,
	}
}

// NewGetImagesConnectorParamsWithContext creates a new GetImagesConnectorParams object
// with the ability to set a context for a request.
func NewGetImagesConnectorParamsWithContext(ctx context.Context) *GetImagesConnectorParams {
	return &GetImagesConnectorParams{
		Context: ctx,
	}
}

// NewGetImagesConnectorParamsWithHTTPClient creates a new GetImagesConnectorParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImagesConnectorParamsWithHTTPClient(client *http.Client) *GetImagesConnectorParams {
	return &GetImagesConnectorParams{
		HTTPClient: client,
	}
}

/* GetImagesConnectorParams contains all the parameters to send to the API endpoint
   for the get images connector operation.

   Typically these are written to a http.Request.
*/
type GetImagesConnectorParams struct {

	// RequestBody.
	RequestBody *models.GetImagesConnectorRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get images connector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImagesConnectorParams) WithDefaults() *GetImagesConnectorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get images connector params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImagesConnectorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get images connector params
func (o *GetImagesConnectorParams) WithTimeout(timeout time.Duration) *GetImagesConnectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get images connector params
func (o *GetImagesConnectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get images connector params
func (o *GetImagesConnectorParams) WithContext(ctx context.Context) *GetImagesConnectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get images connector params
func (o *GetImagesConnectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get images connector params
func (o *GetImagesConnectorParams) WithHTTPClient(client *http.Client) *GetImagesConnectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get images connector params
func (o *GetImagesConnectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestBody adds the requestBody to the get images connector params
func (o *GetImagesConnectorParams) WithRequestBody(requestBody *models.GetImagesConnectorRequestBody) *GetImagesConnectorParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the get images connector params
func (o *GetImagesConnectorParams) SetRequestBody(requestBody *models.GetImagesConnectorRequestBody) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *GetImagesConnectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
