// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MoveVMToRecycleBinReader is a Reader for the MoveVMToRecycleBin structure.
type MoveVMToRecycleBinReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoveVMToRecycleBinReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMoveVMToRecycleBinOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMoveVMToRecycleBinBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMoveVMToRecycleBinOK creates a MoveVMToRecycleBinOK with default headers values
func NewMoveVMToRecycleBinOK() *MoveVMToRecycleBinOK {
	return &MoveVMToRecycleBinOK{}
}

/* MoveVMToRecycleBinOK describes a response with status code 200, with default header values.

Ok
*/
type MoveVMToRecycleBinOK struct {
	Payload []*MoveVMToRecycleBinOKBodyItems0
}

func (o *MoveVMToRecycleBinOK) Error() string {
	return fmt.Sprintf("[POST /move-vm-to-recycle][%d] moveVmToRecycleBinOK  %+v", 200, o.Payload)
}
func (o *MoveVMToRecycleBinOK) GetPayload() []*MoveVMToRecycleBinOKBodyItems0 {
	return o.Payload
}

func (o *MoveVMToRecycleBinOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMoveVMToRecycleBinBadRequest creates a MoveVMToRecycleBinBadRequest with default headers values
func NewMoveVMToRecycleBinBadRequest() *MoveVMToRecycleBinBadRequest {
	return &MoveVMToRecycleBinBadRequest{}
}

/* MoveVMToRecycleBinBadRequest describes a response with status code 400, with default header values.

MoveVMToRecycleBinBadRequest move Vm to recycle bin bad request
*/
type MoveVMToRecycleBinBadRequest struct {
	Payload string
}

func (o *MoveVMToRecycleBinBadRequest) Error() string {
	return fmt.Sprintf("[POST /move-vm-to-recycle][%d] moveVmToRecycleBinBadRequest  %+v", 400, o.Payload)
}
func (o *MoveVMToRecycleBinBadRequest) GetPayload() string {
	return o.Payload
}

func (o *MoveVMToRecycleBinBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*MoveVMToRecycleBinOKBodyItems0 move VM to recycle bin o k body items0
swagger:model MoveVMToRecycleBinOKBodyItems0
*/
type MoveVMToRecycleBinOKBodyItems0 struct {

	// data
	// Required: true
	Data interface{} `json:"data"`

	// task id
	// Required: true
	TaskID *string `json:"task_id"`
}

// Validate validates this move VM to recycle bin o k body items0
func (o *MoveVMToRecycleBinOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTaskID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MoveVMToRecycleBinOKBodyItems0) validateData(formats strfmt.Registry) error {

	if o.Data == nil {
		return errors.Required("data", "body", nil)
	}

	return nil
}

func (o *MoveVMToRecycleBinOKBodyItems0) validateTaskID(formats strfmt.Registry) error {

	if err := validate.Required("task_id", "body", o.TaskID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this move VM to recycle bin o k body items0 based on context it is used
func (o *MoveVMToRecycleBinOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MoveVMToRecycleBinOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MoveVMToRecycleBinOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res MoveVMToRecycleBinOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
