// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IscsiLunSnapshotDeletionParams iscsi lun snapshot deletion params
//
// swagger:model IscsiLunSnapshotDeletionParams
type IscsiLunSnapshotDeletionParams struct {

	// id
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this iscsi lun snapshot deletion params
func (m *IscsiLunSnapshotDeletionParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IscsiLunSnapshotDeletionParams) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this iscsi lun snapshot deletion params based on context it is used
func (m *IscsiLunSnapshotDeletionParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IscsiLunSnapshotDeletionParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IscsiLunSnapshotDeletionParams) UnmarshalBinary(b []byte) error {
	var res IscsiLunSnapshotDeletionParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
